### ISSUE TITLE
More delimiters like semicolon

### ISSUE THREAD

**Issue by pramach** [p2/quicklook-csv#18]
Hi.
I like this addon and use it quite often.
However, I have lots of csv file using the semicolon (;) as delimiter.
As I'm not very familar with C nor having a compiler, would it be possible to add the semiolon as delimiter too, or make it user configurable at all ?

Thx
Wolfgang

**Comment by p2** [comment]
Semicolons are already supported and should be detected automatically. Creating the following file and naming it `test.csv`, the plugin renders it correctly:

```
a;b;c
1;2;3
4;5;6
```

The plugin determines the separator automatically by looking [at the first 1000 characters](https://github.com/p2/quicklook-csv/blob/master/CSVDocument.m#L51) and looking whether commas, tabs, semicolons or pipes occur more often.

**Comment by p2** [comment]
I'll close this since I haven't heard back. Re-open if it's not working for you and add an example file, please.
