### ISSUE TITLE
Update download location

### ISSUE THREAD

**Issue by adidalal** [p2/quicklook-csv#19]
As Google Code will be offline in ~10 days, would you mind hosting the `.dmg` on GitHub instead?

Ref: https://github.com/caskroom/homebrew-cask/issues/17075

**Comment by p2** [comment]
Stuff should still be available in the Google Code Archive later on. Apparently the URLs will change, but I'm not sure to which ones. I'll fix the link when Google Code goes down and will host new downloads somewhere else (don't want to add them to the code repo).

**Comment by adityadalal924** [comment]
You can use the GitHub releases feature and keep the repo source-only
https://github.com/blog/1547-release-your-software

**Comment by p2** [comment]
That's cool, I didn't realize you could do that, thanks!
