### ISSUE TITLE
TAB Delimited file support does not work for files with .tab extension

### ISSUE THREAD

**Issue by p2** [p2/quicklook-csv#3]
_Original author: schli...@gmail.com (March 01, 2010 04:52:40)_

<b>What steps will reproduce the problem?</b>
1. Save tab delimited file as file.tab
2. Attempt quicklook

<b>What is the expected output? What do you see instead?</b>

Quicklook does not work on .tab files. The files are displayed as they
would appear in any text editor, not in a grid format.

<b>What version of the product are you using? On what operating system?</b>

Latest version of quicklook-csv, on os x 10.6.2

<b>Please provide any additional information below.</b>

If the tab delimited file is saved as file.csv, quicklook then works as
expected.

_Original issue: http://code.google.com/p/quicklook-csv/issues/detail?id=3_

**Comment by victor-lin** [comment]
Quicklook does not work for me on files with the `.tab` extension. It works when the extension is changed to `.tsv` or `.csv`.
